apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
data:
  config.py: |
    DEBUG = False
    SECRET_KEY = "your-secret-key"
    DATABASE_URI = "postgresql://user:password@hostname:5432/dbname"
